
package com.dio.calendar;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * "C:\Program Files (x86)\Java\jdk1.7.0_60\bin\wsimport" -keep -verbose http://localhost:8080/soap?wsdl
 */
@WebService(name = "CalendarRemoteServiceSoap", targetNamespace = "http://calendar.dio.com/")
public interface CalendarRemoteServiceSoap {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.dio.calendar.EntryRemoteWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntry", targetNamespace = "http://calendar.dio.com/", className = "com.dio.calendar.GetEntry")
    @ResponseWrapper(localName = "getEntryResponse", targetNamespace = "http://calendar.dio.com/", className = "com.dio.calendar.GetEntryResponse")
    @Action(input = "http://calendar.dio.com/CalendarRemoteServiceSoap/getEntryRequest", output = "http://calendar.dio.com/CalendarRemoteServiceSoap/getEntryResponse")
    public EntryRemoteWrapper getEntry(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.dio.calendar.EntryRemoteWrapper>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntries", targetNamespace = "http://calendar.dio.com/", className = "com.dio.calendar.GetEntries")
    @ResponseWrapper(localName = "getEntriesResponse", targetNamespace = "http://calendar.dio.com/", className = "com.dio.calendar.GetEntriesResponse")
    @Action(input = "http://calendar.dio.com/CalendarRemoteServiceSoap/getEntriesRequest", output = "http://calendar.dio.com/CalendarRemoteServiceSoap/getEntriesResponse")
    public List<EntryRemoteWrapper> getEntries();

}
